/* CinemaVault application logic — UI-independent data, search, sync and actions. */
(function(){
'use strict';
const state={movies:[],cfg:JSON.parse(localStorage.getItem('cv3_cfg')||'{}'),filter:'all',sort:'alpha',currentId:null,rating:0,syncing:false,lastSync:null,request:0,worker:null,workerReady:false};
const CACHE_KEY='cv3_movies', BATCH_SIZE=24;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2);
const runtimeMinutes=r=>{const s=String(r||'');return Number((s.match(/(\d+)\s*h/i)||[0,0])[1])*60+Number((s.match(/(\d+)\s*m/i)||[0,0])[1]);};
const initials=t=>{const w=String(t||'').replace(/[^a-zA-Z0-9\s]/g,'').trim().split(/\s+/).filter(Boolean);return !w.length?'?':w.length===1?w[0].slice(0,2).toUpperCase():(w[0][0]+w[w.length-1][0]).toUpperCase();};
function toast(msg,ms=2600){const el=$('toast');if(!el)return;el.textContent=msg;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),ms);}
function syncDot(mode){const el=$('sync-dot');if(el)el.className='sync-dot'+(mode?' '+mode:'');const label=$('sync-label');if(label)label.textContent=mode==='live'?'Synced':mode==='syncing'?'Syncing…':mode==='err'?'Offline':'Local cache';}
function cacheSave(){if(window.CinemaVaultCache)CinemaVaultCache.setCachedMovies(state.movies).catch(()=>localStorage.setItem(CACHE_KEY,JSON.stringify(state.movies)));else localStorage.setItem(CACHE_KEY,JSON.stringify(state.movies));updateHeaderStats();}
function updateHeaderStats(){const w=state.movies.filter(m=>m.watched).length;if($('hs-total'))$('hs-total').textContent=state.movies.length;if($('hs-watched'))$('hs-watched').textContent=w;if($('hs-left'))$('hs-left').textContent=state.movies.length-w;}
function normalizeMovie(m){return{id:m.id||uid(),title:m.title||'',year:m.year||'',genre:m.genre||'',runtime:m.runtime||'',watched:m.watched==='true'||m.watched===true||m.watched==='TRUE',watchedOn:m.watchedOn||'',verdict:m.verdict||'',technical:m.technical||'',shotLink:m.shotLink||'',rating:parseInt(m.rating)||0};}
async function restoreCache(){let cached=null;try{if(window.CinemaVaultCache)cached=await CinemaVaultCache.getCachedMovies();if(cached&&Array.isArray(cached.data))state.movies=cached.data.map(normalizeMovie);}catch(e){}if(!state.movies.length){try{const raw=localStorage.getItem(CACHE_KEY);if(raw)state.movies=JSON.parse(raw).map(normalizeMovie);}catch(e){}}updateHeaderStats();}
async function syncFromSheets(manual=false){if(!state.cfg.sheetsURL||state.syncing)return;if(manual)toast('Syncing…');state.syncing=true;syncDot('syncing');try{const res=await fetch(state.cfg.sheetsURL+'?t='+Date.now(),{cache:'no-store'});const data=await res.json();if(!data.ok||!Array.isArray(data.movies))throw new Error('Invalid response');state.movies=data.movies.map(normalizeMovie);state.lastSync=new Date();cacheSave();syncDot('live');updateSettingsStatus('ok');render();if(manual)toast('✓ Synced — '+state.movies.length+' titles');}catch(e){syncDot('err');updateSettingsStatus('error');if(manual)toast('Showing local cache — Sheets unavailable');}finally{state.syncing=false;}}
async function pushMovie(movie){if(!state.cfg.sheetsURL||!movie)return;try{await fetch(state.cfg.sheetsURL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain'},body:JSON.stringify({action:'update_one',movie})});state.lastSync=new Date();syncDot('live');updateSettingsStatus('ok');}catch(e){syncDot('err');}}
async function pushMovies(movies){if(!state.cfg.sheetsURL||!movies?.length)return;try{await fetch(state.cfg.sheetsURL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain'},body:JSON.stringify({action:'add_movies',movies})});}catch(e){console.warn('Sheet append failed',e);}}
function localFilterSort(){const q=($('search')?.value||'').trim().toLowerCase();let list=state.movies.filter(m=>(!q||String(m.title).toLowerCase().includes(q)||String(m.genre).toLowerCase().includes(q))&&(state.filter==='watched'?m.watched:state.filter==='unwatched'?!m.watched:true));list.sort((a,b)=>state.sort==='year'?String(b.year).localeCompare(String(a.year)):state.sort==='runtime'?runtimeMinutes(b.runtime)-runtimeMinutes(a.runtime):state.sort==='genre'?String(a.genre).localeCompare(String(b.genre)):String(a.title).localeCompare(String(b.title)));return list;}
function workerFilter(){return new Promise(resolve=>{if(!state.workerReady||!state.worker){resolve(localFilterSort());return;}const requestId=++state.request;const timer=setTimeout(()=>resolve(localFilterSort()),1200);state.worker.onmessage=function(e){if(e.data.requestId!==requestId)return;clearTimeout(timer);resolve(e.data.results||[]);};state.worker.postMessage({requestId,query:$('search')?.value||'',dataset:state.movies,activeFilter:state.filter,activeSort:state.sort});});}
async function initSearchWorker(){try{if(!window.Worker)return;state.worker=new Worker('./searchWorker.js');state.workerReady=true;state.worker.onerror=()=>{state.workerReady=false;};}catch(e){state.worker=null;state.workerReady=false;}}
function render(){updateHeaderStats();renderLibrary();renderHome();renderStats();}
async function renderLibrary(){const list=await workerFilter(),grid=$('movie-grid'),count=$('list-count'),empty=$('empty');if(count)count.textContent=list.length+' titles';if(!grid)return;if(!list.length){grid.innerHTML='';if(empty)empty.hidden=false;return;}if(empty)empty.hidden=true;const frag=document.createDocumentFragment();list.slice(0,BATCH_SIZE).forEach(m=>{const card=document.createElement('article');card.className='movie-card';card.innerHTML=`<div class="movie-poster"><span class="movie-initial">${esc(initials(m.title))}</span>${m.watched?'<span class="watched-mark">✓</span>':''}</div><div class="movie-info"><div class="movie-title">${esc(m.title)}</div><div class="movie-meta">${esc(m.year||'—')} · ${m.rating?'★ '+m.rating:'Unrated'}</div></div>`;card.addEventListener('click',()=>openMovie(m.id));frag.appendChild(card);});grid.replaceChildren(frag);}
function renderHome(){const recent=[...state.movies].slice(0,6),row=$('recent-row');if(row)row.innerHTML=recent.map(m=>`<article class="poster-card" data-id="${esc(m.id)}"><div class="poster-art"><span>${esc(initials(m.title))}</span></div><div>${esc(m.title)}</div><small>${esc(m.year||'')}</small></article>`).join('');row?.querySelectorAll('[data-id]').forEach(el=>el.addEventListener('click',()=>openMovie(el.dataset.id)));const featured=state.movies.find(m=>!m.watched)||state.movies[0];if(featured){$('hero-title').textContent=featured.title;$('hero-meta').textContent=[featured.year,featured.genre,featured.runtime].filter(Boolean).join(' · ');$('hero-open').onclick=()=>openMovie(featured.id);}}
function renderStats(){const w=state.movies.filter(m=>m.watched).length,rated=state.movies.filter(m=>m.rating),avg=rated.length?(rated.reduce((a,m)=>a+m.rating,0)/rated.length).toFixed(1):'—';if($('stat-total'))$('stat-total').textContent=state.movies.length;if($('stat-watched'))$('stat-watched').textContent=w;if($('stat-left'))$('stat-left').textContent=state.movies.length-w;if($('stat-avg'))$('stat-avg').textContent=avg;const map={};state.movies.forEach(m=>String(m.genre||'').split(/[,/·-]/).forEach(g=>{g=g.trim();if(g)map[g]=(map[g]||0)+1;}));const top=Object.entries(map).sort((a,b)=>b[1]-a[1]).slice(0,8),max=top[0]?.[1]||1;if($('genre-bars'))$('genre-bars').innerHTML=top.map(([g,c])=>`<div class="genre-bar"><div><span>${esc(g)}</span><b>${c}</b></div><i><em style="width:${Math.round(c/max*100)}%"></em></i></div>`).join('');}
function openMovie(id){const m=state.movies.find(x=>x.id===id);if(!m)return;state.currentId=id;state.rating=m.rating||0;$('modal-title').textContent=m.title;$('modal-meta').textContent=[m.year,m.genre,m.runtime].filter(Boolean).join(' · ');$('modal-verdict').value=m.verdict||'';$('modal-technical').value=m.technical||'';$('modal-date').value=m.watchedOn||'';$('modal-watched').checked=!!m.watched;document.querySelectorAll('.rating-btn').forEach((b,i)=>b.classList.toggle('sel',i+1===state.rating));$('modal').classList.add('open');}
function closeMovie(){$('modal').classList.remove('open');}
function setRating(n){state.rating=n;document.querySelectorAll('.rating-btn').forEach((b,i)=>b.classList.toggle('sel',i+1===n));}
async function saveMovie(){const m=state.movies.find(x=>x.id===state.currentId);if(!m)return;m.watched=$('modal-watched').checked;m.watchedOn=$('modal-date').value;m.verdict=$('modal-verdict').value.trim();m.technical=$('modal-technical').value.trim();m.rating=state.rating;cacheSave();render();closeMovie();await pushMovie(m);toast('✓ Saved');}
async function deleteMovie(){const m=state.movies.find(x=>x.id===state.currentId);if(!m)return;if(!confirm('Remove “'+m.title+'”?'))return;state.movies=state.movies.filter(x=>x.id!==state.currentId);cacheSave();render();closeMovie();toast('Removed');}
async function quickWatch(id){const m=state.movies.find(x=>x.id===id);if(!m)return;m.watched=!m.watched;if(m.watched&&!m.watchedOn)m.watchedOn=new Date().toISOString().slice(0,10);cacheSave();render();pushMovie(m);}
function addSingle(){const title=$('single-title').value.trim();if(!title){toast('Enter a title');return;}if(state.movies.some(m=>m.title.toLowerCase()===title.toLowerCase())){toast('Already in collection');return;}const m={id:uid(),title,year:$('single-year').value.trim(),runtime:$('single-runtime').value.trim(),genre:$('single-genre').value.trim(),watched:false,rating:0};state.movies.unshift(m);cacheSave();render();pushMovies([m]);['single-title','single-year','single-runtime','single-genre'].forEach(id=>$(id).value='');toast('✓ Added');go('library');}
async function parseBulk(){const raw=$('bulk-input').value.trim();if(!raw){toast('Paste a list first');return;}if(!state.cfg.sheetsURL){toast('Add your Apps Script URL in Settings first');go('settings');return;}const btn=$('parse-btn');btn.disabled=true;btn.textContent='Parsing…';try{const encoded=btoa(unescape(encodeURIComponent(JSON.stringify({action:'ai_parse',text:raw}))));const res=await fetch(state.cfg.sheetsURL+'?payload='+encodeURIComponent(encoded),{cache:'no-store'});const data=await res.json();if(!data.ok)throw new Error(data.error||'Parse failed');window.parsedMovies=data.movies||[];const existing=new Set(state.movies.map(m=>m.title.toLowerCase()));const fresh=window.parsedMovies.filter(m=>!existing.has(String(m.title).toLowerCase()));$('parse-box').style.display='block';$('parse-status').textContent=`${window.parsedMovies.length} found · ${fresh.length} new`;$('parse-items').innerHTML=fresh.slice(0,15).map(m=>`<div class="parse-item"><b>${esc(m.title)}</b><span>${esc([m.year,m.genre].filter(Boolean).join(' · '))}</span></div>`).join('');$('add-parsed').hidden=!fresh.length;$('add-parsed').textContent='Add '+fresh.length+' titles';}catch(e){toast('AI parse error — check Apps Script');}finally{btn.disabled=false;btn.textContent='Parse & clean with AI';}}
function addParsed(){const existing=new Set(state.movies.map(m=>m.title.toLowerCase()));const fresh=(window.parsedMovies||[]).filter(m=>!existing.has(String(m.title).toLowerCase())).map(m=>normalizeMovie({...m,id:uid(),watched:false,rating:0}));state.movies=[...fresh,...state.movies];cacheSave();render();pushMovies(fresh);$('bulk-input').value='';$('parse-box').style.display='none';$('add-parsed').hidden=true;toast('✓ '+fresh.length+' titles added');go('library');}
function importFile(input){const file=input.files?.[0];if(!file)return;if(!window.XLSX){toast('Spreadsheet library unavailable');return;}const reader=new FileReader();reader.onload=e=>{try{const wb=XLSX.read(e.target.result,{type:'array'}),existing=new Set(state.movies.map(m=>m.title.toLowerCase())),added=[];wb.SheetNames.forEach(sn=>XLSX.utils.sheet_to_json(wb.Sheets[sn],{header:1,defval:''}).forEach((row,i)=>{if(i===0)return;const title=String(row[0]||'').trim();if(!title||existing.has(title.toLowerCase()))return;const m=normalizeMovie({id:uid(),title,year:String(row[1]||'').trim(),genre:String(row[2]||'').trim(),runtime:String(row[3]||'').trim(),watchedOn:String(row[4]||'').trim(),verdict:String(row[5]||'').trim(),technical:String(row[6]||'').trim(),shotLink:String(row[7]||'').trim(),watched:!!(row[4]||row[5]),rating:row[8]});state.movies.unshift(m);added.push(m);existing.add(title.toLowerCase());}));cacheSave();render();pushMovies(added);toast('✓ '+added.length+' imported');go('library');}catch(err){toast('Invalid spreadsheet');}};reader.readAsArrayBuffer(file);}
function go(name){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$('screen-'+name)?.classList.add('active');document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.screen===name));if(name==='library')renderLibrary();}
function setFilter(f,el){state.filter=f;document.querySelectorAll('.chip[data-filter]').forEach(x=>x.classList.remove('active'));el.classList.add('active');renderLibrary();}
function setSort(s){state.sort=s;renderLibrary();}
function switchTab(name){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',x.id==='panel-'+name));}
function updateSettingsStatus(mode){const title=$('setting-sync-title'),sub=$('setting-sync-sub');if(!title)return;if(mode==='ok'){title.textContent='Connected to Google Sheets';sub.textContent=state.lastSync?'Last sync: '+state.lastSync.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):'Synced';}else if(mode==='error'){title.textContent='Sync unavailable';sub.textContent='Using local cache';}else{title.textContent='Not connected';sub.textContent='Add your Apps Script URL below';}}
function saveSettings(){const url=$('sheets-url').value.trim();state.cfg.sheetsURL=url;localStorage.setItem('cv3_cfg',JSON.stringify(state.cfg));if(!url){syncDot('');updateSettingsStatus('idle');toast('Settings saved');return;}toast('Saved — syncing…');syncFromSheets(true);}
function exportCSV(){const h=['Title','Year','Genre','Runtime','Watched','Watched On','Verdict','Technical','Best Shot','Rating'];const rows=state.movies.map(m=>[m.title,m.year,m.genre,m.runtime,m.watched?'Yes':'No',m.watchedOn||'',m.verdict||'',m.technical||'',m.shotLink||'',m.rating||''].map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(','));const a=document.createElement('a');a.href='data:text/csv;charset=utf-8,'+encodeURIComponent([h.join(','),...rows].join('\n'));a.download='CinemaVault_'+new Date().toISOString().slice(0,10)+'.csv';a.click();}
function clearAll(){if(!confirm('Delete your local collection?'))return;state.movies=[];if(window.CinemaVaultCache)CinemaVaultCache.clear?.();localStorage.removeItem(CACHE_KEY);render();toast('Collection cleared');}
function bind(){document.querySelectorAll('.nav-item[data-screen]').forEach(n=>n.addEventListener('click',()=>go(n.dataset.screen)));document.querySelectorAll('.tab[data-tab]').forEach(t=>t.addEventListener('click',()=>switchTab(t.dataset.tab)));document.querySelectorAll('[data-go="library"]').forEach(x=>x.addEventListener('click',()=>go('library')));const search=$('search');if(search){let timer;search.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(renderLibrary,60);});}document.querySelectorAll('.chip[data-filter]').forEach(c=>c.addEventListener('click',()=>setFilter(c.dataset.filter,c)));$('sort').addEventListener('change',e=>setSort(e.target.value));$('hero-open').addEventListener('click',()=>{const m=state.movies.find(x=>!x.watched)||state.movies[0];if(m)openMovie(m.id)});$('modal-close').addEventListener('click',closeMovie);$('modal-save').addEventListener('click',saveMovie);$('modal-delete').addEventListener('click',deleteMovie);$('modal').addEventListener('click',e=>{if(e.target===$('modal'))closeMovie()});document.querySelectorAll('.rating-btn').forEach((b,i)=>b.addEventListener('click',()=>setRating(i+1)));$('single-form').addEventListener('submit',e=>{e.preventDefault();addSingle()});$('parse-btn').addEventListener('click',parseBulk);$('add-parsed').addEventListener('click',addParsed);$('file-input').addEventListener('change',e=>importFile(e.target));$('save-settings').addEventListener('click',saveSettings);$('sync-now').addEventListener('click',()=>syncFromSheets(true));$('export-csv').addEventListener('click',exportCSV);$('clear-all').addEventListener('click',clearAll);$('sheets-url').value=state.cfg.sheetsURL||'';}
(async function boot(){bind();await initSearchWorker();await restoreCache();render();setTimeout(()=>document.body.classList.add('ready'),350);if(state.cfg.sheetsURL){updateSettingsStatus('idle');syncFromSheets(false);}setInterval(()=>{if(!document.hidden)syncFromSheets(false)},300000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)syncFromSheets(false)});})();
window.CinemaVault={state,go,openMovie,quickWatch};
})();
